package Furniture.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.TransformationMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Component_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Garage_Project_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Project_Component_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Text_Line_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Warehouse_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<TransformationMenu> getDeclaredDefaultTransformationMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<TransformationMenu>singletonList(new Project_Component_TransformationMenu());
      default:
    }
    return Collections.<TransformationMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xba1c46a5482045d5L, 0x9b2c6521c394c581L, 0x61a1f56ddc201198L), MetaIdFactory.conceptId(0xba1c46a5482045d5L, 0x9b2c6521c394c581L, 0x5418fa6ab58180f0L), MetaIdFactory.conceptId(0xba1c46a5482045d5L, 0x9b2c6521c394c581L, 0x5418fa6ab5818106L), MetaIdFactory.conceptId(0xba1c46a5482045d5L, 0x9b2c6521c394c581L, 0x5418fa6ab58180f6L), MetaIdFactory.conceptId(0xba1c46a5482045d5L, 0x9b2c6521c394c581L, 0x61a1f56ddc201179L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xba1c46a5482045d5L, 0x9b2c6521c394c581L, 0x5418fa6ab5818106L)).seal();
}
