package Furniture.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Component;
  private ConceptPresentation props_Garage_Project;
  private ConceptPresentation props_Project_Component;
  private ConceptPresentation props_Text_Line;
  private ConceptPresentation props_Warehouse;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Component:
        if (props_Component == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Component = cpb.create();
        }
        return props_Component;
      case LanguageConceptSwitch.Garage_Project:
        if (props_Garage_Project == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Garage_Project = cpb.create();
        }
        return props_Garage_Project;
      case LanguageConceptSwitch.Project_Component:
        if (props_Project_Component == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Project component");
          props_Project_Component = cpb.create();
        }
        return props_Project_Component;
      case LanguageConceptSwitch.Text_Line:
        if (props_Text_Line == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Text_Line");
          props_Text_Line = cpb.create();
        }
        return props_Text_Line;
      case LanguageConceptSwitch.Warehouse:
        if (props_Warehouse == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Warehouse");
          props_Warehouse = cpb.create();
        }
        return props_Warehouse;
    }
    return null;
  }
}
