package Furniture.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_Material extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Material() {
    super(0xba1c46a5482045d5L, 0x9b2c6521c394c581L, 0x5418fa6ab58176b5L, "Material", "r:e44b24ff-876f-47eb-9c98-9fe11b493d00(Furniture.structure)/6059868634845640373", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_Maple_0 = new EnumerationDescriptor.MemberDescriptor("Maple", "wood", "r:e44b24ff-876f-47eb-9c98-9fe11b493d00(Furniture.structure)/7035173945122763866", "Maple");
  private final EnumerationDescriptor.MemberDescriptor VALUE_Oak_0 = new EnumerationDescriptor.MemberDescriptor("Oak", "metal", "r:e44b24ff-876f-47eb-9c98-9fe11b493d00(Furniture.structure)/7035173945122763867", "Oak");
  private final EnumerationDescriptor.MemberDescriptor VALUE_Iron_0 = new EnumerationDescriptor.MemberDescriptor("Iron", "iron", "r:e44b24ff-876f-47eb-9c98-9fe11b493d00(Furniture.structure)/7035173945122763872", "Iron");
  private final EnumerationDescriptor.MemberDescriptor VALUE_Steel_0 = new EnumerationDescriptor.MemberDescriptor("Steel", "steel", "r:e44b24ff-876f-47eb-9c98-9fe11b493d00(Furniture.structure)/7035173945122763879", "Steel");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_Steel_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_Maple_0, VALUE_Oak_0, VALUE_Iron_0, VALUE_Steel_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "Maple":
        return VALUE_Maple_0;
      case "Oak":
        return VALUE_Oak_0;
      case "Iron":
        return VALUE_Iron_0;
      case "Steel":
        return VALUE_Steel_0;
    }
    return null;
  }
}
