package CSS.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CSS_Declaration = 0;
  public static final int CSS_Declaration_Block = 1;
  public static final int CSS_File = 2;
  public static final int CSS_Ruleset = 3;
  public static final int CSS_Selector = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb9f4bf860f3d4271L, 0x8f07abe516407b4aL);
    builder.put(0x6fc2a5dc202eb7a3L, CSS_Declaration);
    builder.put(0x6fc2a5dc202eb7a5L, CSS_Declaration_Block);
    builder.put(0x6fc2a5dc202eb7a6L, CSS_File);
    builder.put(0x6fc2a5dc202eb7a7L, CSS_Ruleset);
    builder.put(0x6fc2a5dc202eb7a4L, CSS_Selector);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
